language: node_js
env:
  - TYPESCRIPT_VERSION=3.5
  - TYPESCRIPT_VERSION=3.6
  - TYPESCRIPT_VERSION=3.7
node_js:
  - "11"
script:
  - yarn add typescript@$TYPESCRIPT_VERSION
  - yarn lint
  - yarn test
