language: node_js
env:
  - TYPESCRIPT_VERSION=3.7
  - TYPESCRIPT_VERSION=3.8
  - TYPESCRIPT_VERSION=3.9
  - TYPESCRIPT_VERSION=4.0
  - TYPESCRIPT_VERSION=4.1
node_js:
  - "12"
  - "14"
  - "15"
script:
  - yarn add typescript@$TYPESCRIPT_VERSION
  - yarn lint
  - yarn test
